"use strict";
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
Object.defineProperty(exports, "__esModule", { value: true });
exports.getByPrefix = exports.mdel = exports.mget = exports.mset = exports.del = exports.get = exports.set = void 0;
/* Table schema:
CREATE TABLE kv_store_462e692b (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/
// View at https://supabase.com/dashboard/project/mindpshqgsysshrsgolw/database/tables
// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
const supabase_js_1 = require("@supabase/supabase-js");
const client = () => (0, supabase_js_1.createClient)(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
// Set stores a key-value pair in the database.
const set = async (key, value) => {
    const supabase = client();
    const { error } = await supabase.from("kv_store_462e692b").upsert({
        key,
        value
    });
    if (error) {
        throw new Error(error.message);
    }
};
exports.set = set;
// Get retrieves a key-value pair from the database.
const get = async (key) => {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_462e692b").select("value").eq("key", key).maybeSingle();
    if (error) {
        throw new Error(error.message);
    }
    return data?.value;
};
exports.get = get;
// Delete deletes a key-value pair from the database.
const del = async (key) => {
    const supabase = client();
    const { error } = await supabase.from("kv_store_462e692b").delete().eq("key", key);
    if (error) {
        throw new Error(error.message);
    }
};
exports.del = del;
// Sets multiple key-value pairs in the database.
const mset = async (keys, values) => {
    const supabase = client();
    const { error } = await supabase.from("kv_store_462e692b").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    if (error) {
        throw new Error(error.message);
    }
};
exports.mset = mset;
// Gets multiple key-value pairs from the database.
const mget = async (keys) => {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_462e692b").select("value").in("key", keys);
    if (error) {
        throw new Error(error.message);
    }
    return data?.map((d) => d.value) ?? [];
};
exports.mget = mget;
// Deletes multiple key-value pairs from the database.
const mdel = async (keys) => {
    const supabase = client();
    const { error } = await supabase.from("kv_store_462e692b").delete().in("key", keys);
    if (error) {
        throw new Error(error.message);
    }
};
exports.mdel = mdel;
// Search for key-value pairs by prefix.
const getByPrefix = async (prefix) => {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_462e692b").select("key, value").like("key", prefix + "%");
    if (error) {
        throw new Error(error.message);
    }
    return data?.map((d) => d.value) ?? [];
};
exports.getByPrefix = getByPrefix;
